# Generated by Django 4.0.3 on 2022-04-26 11:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('based_on_level', models.CharField(blank=True, max_length=15, null=True)),
                ('prefered_period', models.CharField(blank=True, max_length=15, null=True)),
                ('creation_date', models.DateTimeField(blank=True, null=True)),
                ('updation_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.CharField(blank=True, max_length=30, null=True)),
                ('contact', models.CharField(blank=True, max_length=10, null=True)),
                ('email', models.EmailField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='School_leaving',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(blank=True, max_length=100, null=True)),
                ('highest_grade', models.CharField(blank=True, max_length=10, null=True)),
                ('exam_year', models.DateField(blank=True, null=True)),
                ('exam_authority', models.CharField(blank=True, max_length=30, null=True)),
                ('application', models.ForeignKey(default='unavailable', on_delete=django.db.models.deletion.CASCADE, to='portal.application')),
            ],
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.EmailField(blank=True, max_length=50, null=True)),
                ('tuition_fee', models.IntegerField(blank=True, null=True)),
                ('registration_fee', models.IntegerField(blank=True, null=True)),
                ('student_fund', models.IntegerField(blank=True, null=True)),
                ('application', models.ForeignKey(default='unavailable', on_delete=django.db.models.deletion.CASCADE, to='portal.application')),
            ],
        ),
        migrations.CreateModel(
            name='School_leaving_subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(blank=True, max_length=30, null=True)),
                ('subject_level', models.CharField(blank=True, max_length=15, null=True)),
                ('symbol', models.CharField(blank=True, max_length=1, null=True)),
                ('point', models.IntegerField(blank=True, null=True)),
                ('application', models.ForeignKey(default='unavailable', on_delete=django.db.models.deletion.CASCADE, to='portal.application')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.school_leaving')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nationality', models.CharField(blank=True, max_length=15, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('date_of_birth', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('id_number', models.IntegerField(blank=True, null=True)),
                ('passport_number', models.CharField(blank=True, max_length=20, null=True)),
                ('passport_expiry_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('permit_number', models.IntegerField(blank=True, null=True)),
                ('permit_type', models.CharField(blank=True, max_length=20, null=True)),
                ('permit_expiry_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('has_medical_condition', models.CharField(blank=True, max_length=3, null=True)),
                ('medical_condition_description', models.TextField(blank=True, max_length=500, null=True)),
                ('application', models.ForeignKey(default='unavailable', on_delete=django.db.models.deletion.CASCADE, to='portal.application')),
            ],
        ),
        migrations.CreateModel(
            name='Post_acadmic_qualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution_name', models.CharField(blank=True, max_length=50, null=True)),
                ('location', models.CharField(blank=True, max_length=50, null=True)),
                ('programme', models.CharField(blank=True, max_length=100, null=True)),
                ('year_start', models.DateField(blank=True, null=True)),
                ('year_end', models.DateField(blank=True, null=True)),
                ('application', models.ForeignKey(default='unavailable', on_delete=django.db.models.deletion.CASCADE, to='portal.application')),
            ],
        ),
        migrations.CreateModel(
            name='Outstanding_result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('out_standing_exam_result', models.CharField(blank=True, max_length=50, null=True)),
                ('out_standing_exam_result_date', models.DateField(blank=True, null=True)),
                ('to_be_taken_exam_result', models.CharField(blank=True, max_length=50, null=True)),
                ('to_be_taken_exam_result_date', models.DateField(blank=True, null=True)),
                ('application', models.ForeignKey(default='unavailable', on_delete=django.db.models.deletion.CASCADE, to='portal.application')),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secondary_school_language', models.CharField(blank=True, max_length=30, null=True)),
                ('home_language', models.CharField(blank=True, max_length=30, null=True)),
                ('english_course', models.CharField(blank=True, max_length=50, null=True)),
                ('applying_english_course', models.CharField(blank=True, max_length=3, null=True)),
                ('application', models.ForeignKey(default='unavailable', on_delete=django.db.models.deletion.CASCADE, to='portal.application')),
            ],
        ),
        migrations.CreateModel(
            name='Kin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('id_number', models.IntegerField(blank=True, null=True)),
                ('relationship_type', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=50, null=True)),
                ('cellphone_number', models.IntegerField(blank=True, null=True)),
                ('telephone', models.IntegerField(blank=True, null=True)),
                ('residential_address', models.TextField(blank=True, max_length=100, null=True)),
                ('postal_address', models.CharField(blank=True, max_length=15, null=True)),
                ('origin_residential_address', models.TextField(blank=True, max_length=100, null=True)),
                ('occupation', models.CharField(blank=True, max_length=50, null=True)),
                ('Work_telephone', models.IntegerField(blank=True, null=True)),
                ('application', models.ForeignKey(default='unavailable', on_delete=django.db.models.deletion.CASCADE, to='portal.application')),
            ],
        ),
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employer_name', models.CharField(blank=True, max_length=50, null=True)),
                ('occupation', models.CharField(blank=True, max_length=50, null=True)),
                ('employer_telephone', models.IntegerField(blank=True, null=True)),
                ('employer_email', models.EmailField(blank=True, max_length=50, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('duties', models.TextField(blank=True, null=True)),
                ('application', models.ForeignKey(default='unavailable', on_delete=django.db.models.deletion.CASCADE, to='portal.application')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('programme', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('tuition_fee', models.IntegerField(blank=True, null=True)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.faculty')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cellphone_number_1', models.IntegerField(blank=True, null=True)),
                ('cellphone_number_2', models.IntegerField(blank=True, null=True)),
                ('namibia_postal_address', models.CharField(blank=True, max_length=15, null=True)),
                ('namibia_residential_address', models.TextField(blank=True, max_length=100, null=True)),
                ('origin_postal_address', models.CharField(blank=True, max_length=15, null=True)),
                ('origin_residential_address', models.TextField(blank=True, max_length=100, null=True)),
                ('telephone', models.IntegerField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=50, null=True)),
                ('application', models.ForeignKey(default='unavailable', on_delete=django.db.models.deletion.CASCADE, to='portal.application')),
            ],
        ),
        migrations.AddField(
            model_name='application',
            name='course_first_choice',
            field=models.ForeignKey(default='unavailable', on_delete=django.db.models.deletion.CASCADE, to='portal.course'),
        ),
        migrations.AddField(
            model_name='application',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
