# Generated by Django 4.0.3 on 2022-05-01 23:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portal', '0003_campus_creation_date_campus_updation_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('subject_code', models.CharField(blank=True, max_length=50, null=True)),
                ('level', models.IntegerField(blank=True, null=True)),
                ('credits', models.IntegerField(blank=True, null=True)),
                ('subject_outline', models.TextField(blank=True, max_length=1000, null=True)),
                ('faculty', models.ForeignKey(default='unavailable', on_delete=django.db.models.deletion.CASCADE, to='portal.faculty')),
                ('lecturer', models.ForeignKey(default='unavailable', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
