# Generated by Django 4.0.3 on 2022-05-01 23:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portal', '0004_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='faculty',
            field=models.ForeignKey(blank=True, default='unavailable', null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.faculty'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='lecturer',
            field=models.ForeignKey(blank=True, default='unavailable', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
