# Generated by Django 4.0.3 on 2022-05-03 08:19

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_remove_campus_location_campus_town_campus_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campus',
            old_name='Town',
            new_name='town',
        ),
        migrations.AddField(
            model_name='campus',
            name='campus_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='campus',
            name='country',
            field=django_countries.fields.CountryField(default='NA', max_length=2),
        ),
    ]
