# Generated by Django 4.0.3 on 2022-05-03 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_rename_town_campus_town_campus_campus_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('level', models.CharField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11')], max_length=3)),
                ('authority', models.CharField(choices=[('NQA', 'Namibia Qualification Authority'), (0, 'Not Accredited')], max_length=5)),
            ],
        ),
        migrations.RemoveField(
            model_name='course',
            name='programme',
        ),
        migrations.AddField(
            model_name='course',
            name='level',
            field=models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portal.programme'),
        ),
    ]
