# Generated by Django 4.0.3 on 2022-05-03 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0009_alter_programme_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programme',
            name='authority',
            field=models.CharField(choices=[('NQA', 'Namibia Qualification Authority'), ('Not Accredited', 'Not Accredited')], max_length=50),
        ),
        migrations.AlterField(
            model_name='programme',
            name='level',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11')], max_length=3),
        ),
    ]
