# Generated by Django 4.0.3 on 2022-05-03 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0014_alter_course_tuition_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='tuition_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
