# Generated by Django 4.0.3 on 2022-05-03 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0015_alter_course_tuition_fee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='years',
            new_name='number_years',
        ),
    ]
