# Generated by Django 4.0.3 on 2022-05-03 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0016_rename_years_course_number_years'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mode_Of_Study',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='mode_of_study',
            field=models.ManyToManyField(to='portal.mode_of_study'),
        ),
    ]
