# Generated by Django 4.0.3 on 2022-05-03 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0017_mode_of_study_course_mode_of_study'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='mode_of_study',
        ),
    ]
