# Generated by Django 4.0.3 on 2022-05-03 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0018_remove_course_mode_of_study'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='mode_of_study',
            field=models.ManyToManyField(to='portal.mode_of_study'),
        ),
        migrations.AddField(
            model_name='mode_of_study',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
