# Generated by Django 4.0.3 on 2022-05-03 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0019_course_mode_of_study_mode_of_study_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='mode_of_study',
            field=models.ManyToManyField(blank=True, null=True, to='portal.mode_of_study'),
        ),
    ]
