# Generated by Django 4.0.3 on 2022-05-03 14:02

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0020_alter_course_mode_of_study'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='mode_of_study',
        ),
        migrations.AddField(
            model_name='course',
            name='mode_of_study',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Full-time', 'Full-time'), ('Part-time', 'Part-time'), ('Online', 'Online')], max_length=26, null=True),
        ),
        migrations.DeleteModel(
            name='Mode_Of_Study',
        ),
    ]
