# Generated by Django 4.0.3 on 2022-05-03 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0021_remove_course_mode_of_study_course_mode_of_study_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
