# Generated by Django 4.0.3 on 2022-05-04 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0023_application_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='course_first_choice',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET('deleted'), to='portal.course'),
        ),
    ]
