# Generated by Django 4.0.3 on 2022-05-04 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0024_alter_application_course_first_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='category',
            field=models.CharField(blank=True, choices=[('Shortcourse', 'Shortcourse'), ('Undergraduate', 'Undergraduate'), ('Postgraduate', 'Postgraduate')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='based_on_level',
            field=models.CharField(blank=True, choices=[('Grade-11', 'Grade-11'), ('Grade-12', 'Grade-12'), ('Mature-age', 'Mature age'), ('Other-qualitication', 'Other Qualitication')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Rejected', 'Rejected'), ('Approved', 'Approved')], max_length=50, null=True),
        ),
    ]
