# Generated by Django 4.0.3 on 2022-05-04 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0026_application_current_step_alter_application_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='category',
            field=models.CharField(blank=True, choices=[('Shortcourse', 'Shortcourse'), ('Undergraduate', 'Undergraduate'), ('Postgraduate', 'Postgraduate')], max_length=50, null=True),
        ),
    ]
