# Generated by Django 4.0.3 on 2022-05-05 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0027_alter_application_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Secondary_course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='portal.course')),
            ],
        ),
    ]
