# Generated by Django 4.0.3 on 2022-05-05 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0028_secondary_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='course_second_choice',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET('deleted'), to='portal.secondary_course'),
        ),
    ]
