# Generated by Django 4.0.3 on 2022-05-05 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0029_application_course_second_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='category',
            field=models.CharField(choices=[('Shortcourse', 'Shortcourse'), ('Undergraduate', 'Undergraduate'), ('Postgraduate', 'Postgraduate')], max_length=50, null=True),
        ),
    ]
