# Generated by Django 4.0.3 on 2022-05-05 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0030_alter_application_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='category',
            field=models.CharField(choices=[('Shortcourse', 'Shortcourse'), ('Undergraduate', 'Undergraduate'), ('Postgraduate', 'Postgraduate')], default=('Shortcourse', 'Shortcourse'), max_length=50),
        ),
    ]
