# Generated by Django 4.0.3 on 2022-05-05 13:09

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0031_alter_application_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='category',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Shortcourse', 'Shortcourse'), ('Undergraduate', 'Undergraduate'), ('Postgraduate', 'Postgraduate')], max_length=50, null=True),
        ),
    ]
