# Generated by Django 4.0.3 on 2022-05-06 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0034_application_submition_date_alter_application_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='updation_date',
        ),
    ]
