# Generated by Django 4.0.3 on 2022-05-10 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0038_alter_school_leaving_subject_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='application',
            field=models.OneToOneField(default='unavailable', on_delete=django.db.models.deletion.CASCADE, to='portal.application'),
        ),
        migrations.AlterField(
            model_name='employer',
            name='application',
            field=models.OneToOneField(default='unavailable', on_delete=django.db.models.deletion.CASCADE, to='portal.application'),
        ),
        migrations.AlterField(
            model_name='kin',
            name='application',
            field=models.OneToOneField(default='unavailable', on_delete=django.db.models.deletion.CASCADE, to='portal.application'),
        ),
        migrations.AlterField(
            model_name='language',
            name='application',
            field=models.OneToOneField(default='unavailable', on_delete=django.db.models.deletion.CASCADE, to='portal.application'),
        ),
        migrations.AlterField(
            model_name='outstanding_result',
            name='application',
            field=models.OneToOneField(default='unavailable', on_delete=django.db.models.deletion.CASCADE, to='portal.application'),
        ),
        migrations.AlterField(
            model_name='post_acadmic_qualification',
            name='application',
            field=models.OneToOneField(default='unavailable', on_delete=django.db.models.deletion.CASCADE, to='portal.application'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='application',
            field=models.OneToOneField(default='unavailable', on_delete=django.db.models.deletion.CASCADE, to='portal.application'),
        ),
        migrations.AlterField(
            model_name='school_leaving',
            name='application',
            field=models.OneToOneField(default='unavailable', on_delete=django.db.models.deletion.CASCADE, to='portal.application'),
        ),
        migrations.AlterField(
            model_name='school_leaving_subject',
            name='application',
            field=models.OneToOneField(default='unavailable', on_delete=django.db.models.deletion.CASCADE, to='portal.application'),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='application',
            field=models.OneToOneField(default='unavailable', on_delete=django.db.models.deletion.CASCADE, to='portal.application'),
        ),
    ]
