# Generated by Django 4.0.3 on 2022-05-11 19:11

from django.db import migrations, models
import django.utils.timezone
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0039_alter_contact_application_alter_employer_application_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='date_of_birth',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], default=('Male', 'Male'), max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='has_medical_condition',
            field=models.CharField(blank=True, choices=[('YES', 'YES'), ('NO', 'NO'), ('MAYBE', 'MAYBE')], default=('YES', 'YES'), max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='nationality',
            field=django_countries.fields.CountryField(default='NA', max_length=2),
        ),
        migrations.AlterField(
            model_name='profile',
            name='passport_expiry_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='permit_expiry_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='permit_type',
            field=models.CharField(blank=True, choices=[('Study', 'Study'), ('Work', 'Work'), ('Diplomatic', 'Diplomatic'), ('Tourism', 'Tourism')], default=('Study', 'Study'), max_length=30, null=True),
        ),
    ]
