# Generated by Django 4.0.3 on 2022-05-11 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0041_alter_application_course_first_choice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='prefered_campus',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET('deleted'), to='portal.campus'),
        ),
    ]
