# Generated by Django 4.0.3 on 2022-05-11 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0043_remove_application_prefered_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='prefered_period',
            field=models.CharField(blank=True, choices=[('Full-time', 'Full-time'), ('Part-time', 'Part-time'), ('Online', 'Online')], max_length=50, null=True),
        ),
    ]
