# Generated by Django 4.0.3 on 2022-05-11 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0044_application_prefered_period'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='prefered_period',
        ),
    ]
