# Generated by Django 4.0.3 on 2022-05-12 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0049_alter_application_course_first_choice_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='prefered_period',
        ),
    ]
