# Generated by Django 4.0.3 on 2022-05-13 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0051_application_prefered_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='title',
            field=models.CharField(blank=True, choices=[('MR', 'MR'), ('MS', 'MS'), ('MRS', 'MRS'), ('DR', 'DR')], default=('MR', 'MR'), max_length=10, null=True),
        ),
    ]
