# Generated by Django 4.0.3 on 2022-05-16 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0053_profile_full_name_profile_surname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('Single', 'Single'), ('Married', 'Married'), ('Divorsed', 'Divorsed'), ('Separated', 'Separated'), ('Widowed', 'Widowed')], default=('Single', 'Single'), max_length=10, null=True),
        ),
    ]
