# Generated by Django 4.0.3 on 2022-05-16 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0054_alter_profile_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('Single', 'Single'), ('Married', 'Married'), ('Divorsed', 'Divorsed'), ('Separated', 'Separated'), ('Widowed', 'Widowed')], default=('Single', 'Single'), max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], default=('Male', 'Male'), max_length=10, null=True),
        ),
    ]
