# Generated by Django 4.0.3 on 2022-05-16 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0055_profile_marital_status_alter_profile_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='has_medical_needs',
            field=models.CharField(blank=True, choices=[('YES', 'YES'), ('NO', 'NO'), ('MAYBE', 'MAYBE')], default=('NO', 'NO'), max_length=20, null=True),
        ),
    ]
