# Generated by Django 4.0.3 on 2022-05-16 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0056_profile_has_medical_needs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='has_medical_condition',
            field=models.CharField(choices=[('YES', 'YES'), ('NO', 'NO'), ('MAYBE', 'MAYBE')], default=('NO', 'NO'), max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='has_medical_needs',
            field=models.CharField(choices=[('YES', 'YES'), ('NO', 'NO'), ('MAYBE', 'MAYBE')], default=('NO', 'NO'), max_length=20),
        ),
    ]
