# Generated by Django 4.0.3 on 2022-05-18 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0060_alter_profile_passport_expiry_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='application',
            new_name='part_of',
        ),
        migrations.AlterField(
            model_name='profile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='permit_expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
