# Generated by Django 4.0.3 on 2022-05-18 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0061_rename_application_profile_part_of_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='part_of',
            new_name='application',
        ),
    ]
