# Generated by Django 4.0.3 on 2022-05-18 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0063_alter_application_prefered_period_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='prefered_period',
            field=models.CharField(blank=True, choices=[('Full-time', 'Full-time'), ('Part-time', 'Part-time'), ('Online', 'Online')], default=('Full-time', 'Full-time'), max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(blank=True, choices=[('In progress', 'In progress'), ('Pending', 'Pending'), ('Rejected', 'Rejected'), ('Approved', 'Approved')], default=('In progress', 'In progress'), max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='has_medical_condition',
            field=models.CharField(blank=True, choices=[('NO', 'NO'), ('YES', 'YES')], default=('YES', 'YES'), max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='has_medical_needs',
            field=models.CharField(blank=True, choices=[('NO', 'NO'), ('YES', 'YES')], default=('YES', 'YES'), max_length=20, null=True),
        ),
    ]
