# Generated by Django 4.0.3 on 2022-05-18 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0064_alter_application_prefered_period_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='title',
            field=models.CharField(blank=True, choices=[('MR', 'MR'), ('MS', 'MS'), ('MRS', 'MRS'), ('DR', 'DR')], default=('MR', 'MR'), max_length=10),
        ),
    ]
