# Generated by Django 4.0.3 on 2022-05-18 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0065_alter_profile_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='prefered_period',
            field=models.CharField(choices=[('Full-time', 'Full-time'), ('Part-time', 'Part-time'), ('Online', 'Online')], default=('Full-time', 'Full-time'), max_length=50),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('In progress', 'In progress'), ('Pending', 'Pending'), ('Rejected', 'Rejected'), ('Approved', 'Approved')], default=('In progress', 'In progress'), max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default=('Male', 'Male'), max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='has_medical_condition',
            field=models.CharField(choices=[('NO', 'NO'), ('YES', 'YES')], default=('YES', 'YES'), max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='has_medical_needs',
            field=models.CharField(choices=[('NO', 'NO'), ('YES', 'YES')], default=('YES', 'YES'), max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='marital_status',
            field=models.CharField(choices=[('Single', 'Single'), ('Married', 'Married'), ('Divorsed', 'Divorsed'), ('Separated', 'Separated'), ('Widowed', 'Widowed')], default=('Single', 'Single'), max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='permit_type',
            field=models.CharField(choices=[('Study', 'Study'), ('Work', 'Work'), ('Diplomatic', 'Diplomatic'), ('Tourism', 'Tourism')], default=('Study', 'Study'), max_length=30),
        ),
        migrations.AlterField(
            model_name='profile',
            name='title',
            field=models.CharField(choices=[('MR', 'MR'), ('MS', 'MS'), ('MRS', 'MRS'), ('DR', 'DR')], default=('MR', 'MR'), max_length=10),
        ),
    ]
