# Generated by Django 4.0.3 on 2022-05-18 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0070_alter_application_prefered_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='prefered_period',
            field=models.CharField(choices=[('Full-time', 'Full-time'), ('Part-time', 'Part-time'), ('Online', 'Online')], default='Part-time', max_length=50),
        ),
    ]
