# Generated by Django 4.0.3 on 2022-05-18 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0072_alter_application_prefered_period'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kin',
            name='origin_residential_address',
        ),
        migrations.AddField(
            model_name='kin',
            name='title',
            field=models.CharField(choices=[('MR', 'MR'), ('MS', 'MS'), ('MRS', 'MRS'), ('DR', 'DR')], default=('MR', 'MR'), max_length=10),
        ),
        migrations.AlterField(
            model_name='kin',
            name='relationship_type',
            field=models.CharField(choices=[('Parent', 'Parent'), ('Spouse', 'Spouse'), ('Guardian', 'Guardian')], default=('Parent', 'Parent'), max_length=15),
        ),
        migrations.AlterField(
            model_name='profile',
            name='has_medical_condition',
            field=models.CharField(choices=[('NO', 'NO'), ('YES', 'YES')], default='NO', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='has_medical_needs',
            field=models.CharField(choices=[('NO', 'NO'), ('YES', 'YES')], default='NO', max_length=20),
        ),
    ]
