# Generated by Django 4.0.3 on 2022-05-18 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0073_remove_kin_origin_residential_address_kin_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kin',
            name='id_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
