# Generated by Django 4.0.3 on 2022-05-19 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0074_alter_kin_id_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school_leaving',
            name='exam_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
