# Generated by Django 4.0.3 on 2022-05-19 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0076_rename_name_sponsor_postal_address_sponsor_cellphone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsor',
            name='sponsor_signatory_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='sponsor_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
