# Generated by Django 4.0.3 on 2022-05-22 21:19

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0079_sponsor_total_fee'),
    ]

    operations = [
        migrations.CreateModel(
            name='TermsAndConditions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('general', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
