# Generated by Django 4.0.3 on 2022-05-22 21:23

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0080_termsandconditions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='termsandconditions',
            name='general',
        ),
        migrations.AddField(
            model_name='termsandconditions',
            name='general_rule',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
