# Generated by Django 4.0.3 on 2022-05-22 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0081_remove_termsandconditions_general_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='termsandconditions',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
