# Generated by Django 4.0.3 on 2022-05-23 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0084_alter_contact_telephone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='current_step',
            field=models.PositiveSmallIntegerField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(blank=True, max_length=50, null=True),
        ),
    ]
