# Generated by Django 4.0.3 on 2022-05-23 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0089_alter_application_current_step'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='current_step',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
    ]
