# Generated by Django 4.0.3 on 2022-05-23 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0091_alter_application_current_step'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acknowledgement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_form_acknowledgement', models.BooleanField()),
                ('application', models.OneToOneField(default='unavailable', on_delete=django.db.models.deletion.CASCADE, to='portal.application')),
            ],
        ),
    ]
