# Generated by Django 4.0.3 on 2022-05-23 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0094_alter_acknowledgement_application_form_acknowledgement'),
    ]

    operations = [
        migrations.AddField(
            model_name='termsandconditions',
            name='application',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.application'),
        ),
        migrations.AddField(
            model_name='termsandconditions',
            name='application_form_acknowledgement',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Acknowledgement',
        ),
    ]
