# Generated by Django 4.0.3 on 2022-05-23 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0095_termsandconditions_application_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kin',
            old_name='cellphone_number',
            new_name='kin_cellphone_number',
        ),
        migrations.RenameField(
            model_name='kin',
            old_name='email',
            new_name='kin_email',
        ),
        migrations.RenameField(
            model_name='kin',
            old_name='telephone',
            new_name='kin_telephone',
        ),
    ]
