# Generated by Django 4.0.3 on 2022-05-23 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0096_rename_cellphone_number_kin_kin_cellphone_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kin',
            old_name='postal_address',
            new_name='kin_postal_address',
        ),
        migrations.RenameField(
            model_name='kin',
            old_name='residential_address',
            new_name='kin_residential_address',
        ),
        migrations.RenameField(
            model_name='sponsor',
            old_name='cellphone',
            new_name='sponsor_cellphone',
        ),
        migrations.RenameField(
            model_name='sponsor',
            old_name='email',
            new_name='sponsor_email',
        ),
        migrations.RenameField(
            model_name='sponsor',
            old_name='postal_address',
            new_name='sponsor_postal_address',
        ),
        migrations.RenameField(
            model_name='sponsor',
            old_name='telephone',
            new_name='sponsor_telephone',
        ),
    ]
