# Generated by Django 4.0.3 on 2022-05-24 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0097_rename_postal_address_kin_kin_postal_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('In progress', 'In progress'), ('Pending', 'Pending'), ('Rejected', 'Rejected'), ('Approved', 'Approved'), ('Cancelled', 'Cancelled')], default=('In progress', 'In progress'), max_length=50),
        ),
    ]
