# Generated by Django 4.0.3 on 2022-05-25 23:52

from django.db import migrations, models
import django.db.models.deletion
import portal.models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0098_alter_application_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medical_documents', models.FileField(blank=True, null=True, upload_to=portal.models.user_directory_path)),
                ('certified_id_copy', models.FileField(blank=True, null=True, upload_to=portal.models.user_directory_path)),
                ('passport_photo', models.FileField(blank=True, null=True, upload_to=portal.models.user_directory_path)),
                ('evidence_of_payment', models.FileField(blank=True, null=True, upload_to=portal.models.user_directory_path)),
                ('foreign_qualification', models.FileField(blank=True, null=True, upload_to=portal.models.user_directory_path)),
                ('foreign_qualification_translation', models.FileField(blank=True, null=True, upload_to=portal.models.user_directory_path)),
                ('namibia_highest_qualification_copy', models.FileField(blank=True, null=True, upload_to=portal.models.user_directory_path)),
                ('other_documents', models.FileField(blank=True, null=True, upload_to=portal.models.user_directory_path)),
                ('application', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.application')),
            ],
        ),
    ]
