# Generated by Django 4.0.3 on 2022-06-05 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0101_alter_document_certified_id_copy'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='programme',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET('deleted'), to='portal.programme'),
        ),
    ]
