# Generated by Django 4.0.3 on 2022-06-09 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0104_profile_namibian_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='namibian_region',
            field=models.CharField(choices=[('Erongo', 'Erongo'), ('Hardap', 'Hardap'), ('Karas', 'Karas'), ('Khomas', 'Khomas'), ('Kunene', 'Kunene'), ('Kavango East', 'Kavango East'), ('Kavango West', 'Kavango West'), ('Otjozondjupa', 'Otjozondjupa'), ('Oshana', 'Oshana'), ('Oshikoto', 'Oshikoto'), ('Omusati', 'Omusati'), ('Zambezi', 'Zambezi'), ('Omaheke', 'Omaheke'), ('Ohangwena', 'Ohangwena')], default=('Erongo', 'Erongo'), max_length=50, null=True),
        ),
    ]
