# Generated by Django 4.0.3 on 2022-06-09 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0105_alter_profile_namibian_region'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kin',
            old_name='id_number',
            new_name='kin_id_number',
        ),
    ]
