# Generated by Django 4.0.3 on 2022-06-09 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0106_rename_id_number_kin_kin_id_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kin',
            old_name='title',
            new_name='kin_title',
        ),
    ]
