# Generated by Django 4.0.3 on 2022-06-09 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0107_rename_title_kin_kin_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='post_acadmic_qualification',
            name='has_past_qualification',
            field=models.CharField(choices=[('NO', 'NO'), ('YES', 'YES')], default=('NO', 'NO'), max_length=20),
        ),
    ]
