# Generated by Django 4.0.3 on 2022-06-09 21:52

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0108_post_acadmic_qualification_has_past_qualification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_acadmic_qualification',
            name='location',
            field=django_countries.fields.CountryField(blank=True, default='NA', max_length=2, null=True),
        ),
    ]
