# Generated by Django 4.0.3 on 2022-06-09 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0109_alter_post_acadmic_qualification_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post_acadmic_qualification',
            old_name='programme',
            new_name='post_qualification',
        ),
    ]
