# Generated by Django 4.0.3 on 2022-06-09 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0110_rename_programme_post_acadmic_qualification_post_qualification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_acadmic_qualification',
            name='year_end',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post_acadmic_qualification',
            name='year_start',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
