# Generated by Django 4.0.3 on 2022-06-09 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0113_rename_has_out_standing_exam_result_outstanding_result_has_out_standing_exam_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='language',
            name='secondary_school_language',
        ),
        migrations.AddField(
            model_name='language',
            name='has_english_course',
            field=models.CharField(choices=[('NO', 'NO'), ('YES', 'YES')], default=('NO', 'NO'), max_length=20),
        ),
        migrations.AddField(
            model_name='language',
            name='school_language',
            field=models.CharField(choices=[('English', 'English'), ('Oshiherero', 'Oshiherero'), ('Damara / Nama', 'Damara / Nama'), ('AfriKaans', 'AfriKaans'), ('Portuguese', 'Portuguese'), ('French', 'French'), ('Spanish', 'Spanish'), ('German', 'German'), ('Russian', 'Russian'), ('Chinise / Mandarine', 'Chinise / Mandarine'), ('Other', 'Other')], default=('English', 'English'), max_length=50),
        ),
        migrations.AlterField(
            model_name='language',
            name='applying_english_course',
            field=models.CharField(choices=[('NO', 'NO'), ('YES', 'YES')], default=('NO', 'NO'), max_length=20),
        ),
        migrations.AlterField(
            model_name='language',
            name='home_language',
            field=models.CharField(choices=[('English', 'English'), ('Oshiherero', 'Oshiherero'), ('Damara / Nama', 'Damara / Nama'), ('AfriKaans', 'AfriKaans'), ('Portuguese', 'Portuguese'), ('French', 'French'), ('Spanish', 'Spanish'), ('German', 'German'), ('Russian', 'Russian'), ('Chinise / Mandarine', 'Chinise / Mandarine'), ('Other', 'Other')], default=('English', 'English'), max_length=50),
        ),
    ]
