# Generated by Django 4.0.3 on 2022-06-10 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0115_alter_outstanding_result_has_out_standing_exam'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kin',
            old_name='occupation',
            new_name='kin_occupation',
        ),
    ]
