# Generated by Django 4.0.3 on 2022-06-10 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0122_alter_post_acadmic_qualification_has_past_qualification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='applying_english_course',
            field=models.CharField(choices=[('NO', 'NO'), ('YES', 'YES')], default='NO', max_length=20),
        ),
        migrations.AlterField(
            model_name='language',
            name='has_english_course',
            field=models.CharField(choices=[('NO', 'NO'), ('YES', 'YES')], default='NO', max_length=20),
        ),
    ]
