from django.urls import path
from . import views

urlpatterns = [
    path('', views.dashboard, name='portal-dashboard'),
    path('dashboard', views.dashboard, name='portal-dashboard'),
    path('registration-form-undergraduate',
         views.applicationFormUndergraduate,
         name='portal-registration-form-undergraduate'),
    path('registration-form-undergraduate-update',
         views.applicationFormUndergraduate,
         name='portal-registration-form-undergraduate-update'),
    path('registration-form-shortcourse',
         views.applicationFormShortcourse,
         name='portal-registration-form-shortcourse'),
    path('registration-form-shortcourse-update',
         views.applicationFormShortcourse,
         name='portal-registration-form-shortcourse-update'),
    #     path('registration-form-shortcourse-update/<pk>',
    #          views.applicationFormShortcourseUpdate,
    #          name='portal-registration-form-shortcourse-update'),
    path('registration-form-Postgraduate',
         views.applicationFormPostgraduate,
         name='portal-registration-form-Postgraduate'),
    path('application-home',
         views.applicationHome,
         name='portal-application-home'),
    path('profile', views.userProfile, name='portal-user-profile'),
    path('faculty', views.faculty, name='portal-faculty'),
    path('course', views.course, name='portal-course'),
    path('course-update/<course_id>',
         views.course_update,
         name='portal-course-update'),
    path('course-delete/<course_id>',
         views.course_delete,
         name='portal-course-delete'),
    path('faculty-update/<faculty_id>',
         views.faculty_update,
         name='portal-faculty-update'),
    path('faculty-delete/<faculty_id>',
         views.faculty_delete,
         name='portal-faculty-delete'),
    path('404', views.unavailable_page, name='portal-unavailable'),
    path('users', views.users, name='portal-users'),
    path('campus', views.campus, name='portal-campus'),
    path('campus-update/<campus_id>',
         views.campus_update,
         name='portal-campus-update'),
    path('campus-delete/<campus_id>',
         views.campus_delete,
         name='portal-campus-delete'),
    path('subject', views.subject, name='portal-subject'),
    path('campus-view/<campus_id>',
         views.campus_view,
         name='portal-campus-view'),
    path('subject-delete/<subject_id>',
         views.subject_delete,
         name='portal-subject-delete'),
    path('subject-update/<subject_id>',
         views.subject_update,
         name='portal-subject-update'),
    path('faq-create', views.faq_create, name='portal-faq-create'),
    path('terms-and-conditions-create',
         views.terms_conditions_create,
         name='portal-terms-and-conditions-create'),
    path('application-forms',
         views.application_form,
         name='portal-application-forms'),
    #     path('application-forms',
    #          views.application_form,
    #          name='portal-application-forms'),
    path('ajax/oad-courses', views.load_courses,
         name='ajax_load_courses'),  #ajax request courses
    path('application-form-view/<application_id>',
         views.application_form_view,
         name='portal-application-form-view'),
    path('application-form-update/<application_id>',
         views.application_form_update,
         name='portal-application-form-update'),
]